FROM node:22.0.0-alpine3.19 AS build
ARG ARG_TWILIO_ACCOUNT_SID
ARG ARG_TWILIO_API_KEY
ARG ARG_TWILIO_API_SECRET
ARG ARG_TWILIO_TWIML_APP_SID
ARG ARG_TWILIO_ALLOW_INCOMING_CALLS
ARG ARG_TWILIO_AUTH_TOKEN
ARG ARG_FROM_NUMBER
ARG ARG_AGENT_ID
ARG ARG_MONGO_URL
ARG ARG_USER_CONTROLL
ARG ARG_EMAIL_HOST
ARG ARG_EMAIL_PORT
ARG ARG_EMAIL_USERNAME
ARG ARG_EMAIL_PASSWORD
ENV TWILIO_ACCOUNT_SID $ARG_TWILIO_ACCOUNT_SID
ENV TWILIO_API_KEY $ARG_TWILIO_API_KEY
ENV TWILIO_API_SECRET $ARG_TWILIO_API_SECRET
ENV TWILIO_TWIML_APP_SID $ARG_TWILIO_TWIML_APP_SID
ENV TWILIO_ALLOW_INCOMING_CALLS $ARG_TWILIO_ALLOW_INCOMING_CALLS
ENV TWILIO_AUTH_TOKEN $ARG_TWILIO_AUTH_TOKEN
ENV FROM_NUMBER $ARG_FROM_NUMBER
ENV AGENT_ID $ARG_AGENT_ID
ENV MONGO_URL $ARG_MONGO_URL
ENV USER_CONTROLL $ARG_USER_CONTROLL
ENV EMAIL_HOST $ARG_EMAIL_HOST
ENV EMAIL_PORT $ARG_EMAIL_PORT
ENV EMAIL_USERNAME $ARG_EMAIL_USERNAME
ENV EMAIL_PASSWORD $ARG_EMAIL_PASSWORD
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN apk add --no-cache --virtual .gyp python3 make g++ git
RUN yarn install && yarn cache clean
RUN yarn run build
RUN apk del .gyp

FROM node:22.0.0-alpine3.19 AS run
ARG ARG_TWILIO_ACCOUNT_SID
ARG ARG_TWILIO_API_KEY
ARG ARG_TWILIO_API_SECRET
ARG ARG_TWILIO_TWIML_APP_SID
ARG ARG_TWILIO_ALLOW_INCOMING_CALLS
ARG ARG_TWILIO_AUTH_TOKEN
ARG ARG_FROM_NUMBER
ARG ARG_AGENT_ID
ARG ARG_MONGO_URL
ARG ARG_USER_CONTROLL
ARG ARG_EMAIL_HOST
ARG ARG_EMAIL_PORT
ARG ARG_EMAIL_USERNAME
ARG ARG_EMAIL_PASSWORD
ENV TWILIO_ACCOUNT_SID $ARG_TWILIO_ACCOUNT_SID
ENV TWILIO_API_KEY $ARG_TWILIO_API_KEY
ENV TWILIO_API_SECRET $ARG_TWILIO_API_SECRET
ENV TWILIO_TWIML_APP_SID $ARG_TWILIO_TWIML_APP_SID
ENV TWILIO_ALLOW_INCOMING_CALLS $ARG_TWILIO_ALLOW_INCOMING_CALLS
ENV TWILIO_AUTH_TOKEN $ARG_TWILIO_AUTH_TOKEN
ENV FROM_NUMBER $ARG_FROM_NUMBER
ENV AGENT_ID $ARG_AGENT_ID
ENV MONGO_URL $ARG_MONGO_URL
ENV USER_CONTROLL $ARG_USER_CONTROLL
ENV EMAIL_HOST $ARG_EMAIL_HOST
ENV EMAIL_PORT $ARG_EMAIL_PORT
ENV EMAIL_USERNAME $ARG_EMAIL_USERNAME
ENV EMAIL_PASSWORD $ARG_EMAIL_PASSWORD
EXPOSE 6060
RUN apk add dumb-init git
WORKDIR /usr/src/app
COPY --chown=node:node --from=build /usr/src/app/build /usr/src/app/build
COPY --chown=node:node package.json /usr/src/app/
COPY --chown=node:node tsconfig.json /usr/src/app/
COPY --chown=node:node declarations.d.ts /usr/src/app/
COPY --chown=node:node . .
RUN yarn install --production && yarn cache clean
USER node
CMD ["dumb-init", "yarn", "run", "prod"]